# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('declinazione', models.CharField(choices=[('declinazioni', (('prima declinazione (ae)', 'prima_declinazione'), ('seconda declinazione (i)', 'seconda_declinazione'), ('terza declinazione (is)', 'terza_declinazione'), ('quarta declinazione (us)', 'quarta_declinazione'), ('quinta declinazione (ei)', 'quinta_declinazione'))), ('coniugazione', (('prima', 'prima_coniugazione'), ('seconda', 'seconda_coniugazione'), ('terza', 'terza_coniugazione'), ('quarta', 'quarta_coniugazione'), ('mista', 'mista_coniugazione'))), ('aggettivo', (('prima classe', 'prima_classe'), ('seconda classe', 'seconda_classe'))), ('invariabile', ('invariabile', 'invariabile'))], default='prima declinazione (ae)', max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
