# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180719_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='significato',
            field=models.CharField(default='inserisci significato', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nome',
            name='declinazione',
            field=models.CharField(choices=[('prima declinazione (ae)', 'prima declinazione (ae)'), ('seconda declinazione (i)', 'seconda declinazione (i)'), ('terza declinazione (is)', 'terza declinazione (is)'), ('quarta declinazione (us)', 'quarta declinazione (us)'), ('quinta declinazione (ei)', 'quinta declinazione (ei)'), ('prima coniugazione', 'prima coniugazione'), ('seconda coniugazione', 'seconda coniugazione'), ('terza coniugazione', 'terza coniugazione'), ('quarta coniugazione', 'quarta coniugazione'), ('coniugazione mista', 'coniugazione mista'), ('prima classe', 'aggettivo prima classe'), ('seconda classe', 'aggettivo seconda classe'), ('invariabile', 'invariabile')], default='prima declinazione (ae)', max_length=45),
        ),
    ]
