# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20180719_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
