# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_declina'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='particolarita',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=3),
        ),
    ]
