# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_nome_particolarita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='particolarita',
            field=models.CharField(choices=[(b'si', b'si'), (b'no', b'no')], default=b'no', max_length=3),
        ),
    ]
