# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20180722_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declinazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativosingolare', models.CharField(max_length=100)),
                ('nominativoplurale', models.CharField(max_length=100)),
                ('genitivosingolare', models.CharField(max_length=100)),
                ('genitivoplurale', models.CharField(max_length=100)),
                ('dativosingolare', models.CharField(max_length=100)),
                ('dativoplurale', models.CharField(max_length=100)),
                ('accusativosingolare', models.CharField(max_length=100)),
                ('accusativoplurale', models.CharField(max_length=100)),
                ('vocativosingolare', models.CharField(max_length=100)),
                ('vocativoplurale', models.CharField(max_length=100)),
                ('ablativosingolare', models.CharField(max_length=100)),
                ('ablativoplurale', models.CharField(max_length=100)),
            ],
        ),
    ]
