# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_declinazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='declinazione',
            name='nome',
            field=models.CharField(default='primadeclinazione', max_length=100),
            preserve_default=False,
        ),
    ]
