# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_declinazione_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='declinazione',
            name='ablativopluraleNeutro',
            field=models.CharField(default='is', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='ablativosingolareNeutro',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='accusativopluraleNeutro',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='accusativosingolareNeutro',
            field=models.CharField(default='um', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='dativopluraleNeutro',
            field=models.CharField(default='is', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='dativosingolareNeutro',
            field=models.CharField(default='ae', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='genitivopluraleNeutro',
            field=models.CharField(default='arum', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='genitivosingolareNeutro',
            field=models.CharField(default='ae', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='nominativopluraleNeutro',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='nominativosingolareNeutro',
            field=models.CharField(default='um', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='vocativopluraleNeutro',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declinazione',
            name='vocativosingolareNeutro',
            field=models.CharField(default='um', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nome',
            name='genere',
            field=models.CharField(choices=[('maschile', 'maschile'), ('femminile', 'femminile'), ('neutro', 'neutro')], default='femminile', max_length=50),
        ),
    ]
